Add a bunch of aliases

diff --git a/zsh/aliases b/zsh/aliases
--- a/zsh/aliases
+++ b/zsh/aliases
@@ -1,14 +1,6 @@
 alias ta='tmux attach'
 alias tls='tmux list-sessions'
-alias im='vim'
-alias vimrc='vim ~/.vim/vimrc'
-alias :q='exit'
-alias :Q='exit'
-alias ibrew='arch -x86_64 brew'
-alias mkdirdate='mkdir "$(date +"%Y-%m-%d")"'
 alias v='nvim'
-alias vn='~/.local/bin/neovim-nightly/nvim-macos/bin/nvim'
-alias bat='batcat'
 
 case `uname` in
   Darwin)
@@ -20,13 +12,24 @@ case `uname` in
     alias ctags="`brew --prefix`/bin/ctags"
   ;;
   Linux)
-	alias l='ls -G --color --group-directories-first'
-	alias la='ls -aG --color --group-directories-first'
-	alias lsa='ls -aG --color --group-directories-first'
-	alias ll='ls -lhG --color --group-directories-first'
-	alias lla='ls -alhG --color --group-directories-first'
-	# jwt.show log for datam.at
-	alias jwtlog='sudo bash zcat -f /var/log/nginx/jwt.show.access.log* | goaccess'
+  alias ls='eza -lh --group-directories-first --icons=auto'
+  alias lsa='ls -a'
+  alias lt='eza --tree --level=2 --long --icons --git'
+  alias lta='lt -a'
+
+  alias cd="zd"
+  zd() {
+    if [ $# -eq 0 ]; then
+      builtin cd ~ && return
+    elif [ -d "$1" ]; then
+      builtin cd "$1"
+    else
+      z "$@" && printf " \U000F17A9 " && pwd || echo "Error: Directory not found"
+    fi
+  }
+  open() {
+    xdg-open "$@" >/dev/null 2>&1
+  }
   ;;
 esac
 
@@ -39,3 +42,10 @@ function yazi_cwd() {
     rm -f -- "$tmp"
 }
 alias f='yazi_cwd'
+
+alias l='lazygit'
+
+# Directories
+alias ..='cd ..'
+alias ...='cd ../..'
+alias ....='cd ../../..'
